name: Build
on: [push]
jobs:
  Coq-Build:
    runs-on: ubuntu-latest  # container actions require GNU/Linux
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build
      - run: nix flake check
